---
name: Pre-commit

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
